package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 18, 2015 12:34:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Artist generated by hbm2java
 */
public class Artist implements java.io.Serializable {

	private String name;
	private Set<MusicContent> musicContents = new HashSet<MusicContent>(0);

	public Artist() {
	}

	public Artist(String name) {
		this.name = name;
	}

	public Artist(String name, Set<MusicContent> musicContents) {
		this.name = name;
		this.musicContents = musicContents;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<MusicContent> getMusicContents() {
		return this.musicContents;
	}

	public void setMusicContents(Set<MusicContent> musicContents) {
		this.musicContents = musicContents;
	}

}
