package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 18, 2015 12:34:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private MusicContent musicContent;
	private User user;
	private String commentText;
	private Date commentingTime;
	private Integer musicContentId;
	private Integer userId;
	

	public Comment() {
	}

	public Comment(MusicContent musicContent, User user, String commentText,
			Date commentingTime) {
		this.musicContent = musicContent;
		this.user = user;
		this.commentText = commentText;
		this.commentingTime = commentingTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MusicContent getMusicContent() {
		return this.musicContent;
	}

	public void setMusicContent(MusicContent musicContent) {
		this.musicContent = musicContent;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCommentText() {
		return this.commentText;
	}

	public void setCommentText(String commentText) {
		this.commentText = commentText;
	}

	public Date getCommentingTime() {
		return this.commentingTime;
	}

	public void setCommentingTime(Date commentingTime) {
		this.commentingTime = commentingTime;
	}
	
	public Integer getMusicContentId() {
		return musicContentId;
	}

	public void setMusicContentId(Integer musicContentId) {
		this.musicContentId = musicContentId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
