package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 13, 2015 10:37:52 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Favorite generated by hbm2java
 */
public class Favorite implements java.io.Serializable {

	private Integer id;
	private MusicContent musicContent;
	private User user;
	private Date favoritingTime;

	public Favorite() {
	}

	public Favorite(MusicContent musicContent, User user, Date favoritingTime) {
		this.musicContent = musicContent;
		this.user = user;
		this.favoritingTime = favoritingTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MusicContent getMusicContent() {
		return this.musicContent;
	}

	public void setMusicContent(MusicContent musicContent) {
		this.musicContent = musicContent;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getFavoritingTime() {
		return this.favoritingTime;
	}

	public void setFavoritingTime(Date favoritingTime) {
		this.favoritingTime = favoritingTime;
	}

}
