package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 18, 2015 12:34:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Listening generated by hbm2java
 */
public class Listening implements java.io.Serializable {

	private Integer id;
	private MusicContent musicContent;
	private User user;
	private Date listeningTime;
	private Integer musicContentId;
	private Integer userId;

	public Listening() {
	}

	public Listening(MusicContent musicContent, User user, Date listeningTime) {
		this.musicContent = musicContent;
		this.user = user;
		this.listeningTime = listeningTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MusicContent getMusicContent() {
		return this.musicContent;
	}

	public void setMusicContent(MusicContent musicContent) {
		this.musicContent = musicContent;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getListeningTime() {
		return this.listeningTime;
	}

	public void setListeningTime(Date listeningTime) {
		this.listeningTime = listeningTime;
	}
	
	public Integer getMusicContentId() {
		return musicContentId;
	}

	public void setMusicContentId(Integer musicContentId) {
		this.musicContentId = musicContentId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
