package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 18, 2015 12:34:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Rate generated by hbm2java
 */
public class Rate implements java.io.Serializable {

	private Integer id;
	private MusicContent musicContent;
	private User user;
	private Integer rate;
	private Date ratingTime;
	private Integer musicContentId;
	private Integer userId;

	public Rate() {
	}

	public Rate(MusicContent musicContent, User user, int rate, Date ratingTime) {
		this.musicContent = musicContent;
		this.user = user;
		this.rate = rate;
		this.ratingTime = ratingTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MusicContent getMusicContent() {
		return this.musicContent;
	}

	public void setMusicContent(MusicContent musicContent) {
		this.musicContent = musicContent;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	public Date getRatingTime() {
		return this.ratingTime;
	}

	public void setRatingTime(Date ratingTime) {
		this.ratingTime = ratingTime;
	}

	public Integer getMusicContentId() {
		return musicContentId;
	}

	public void setMusicContentId(Integer musicContentId) {
		this.musicContentId = musicContentId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}
