package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 18, 2015 12:34:37 PM by Hibernate Tools 4.3.1

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private RoleId id;
	private User user;

	public Role() {
	}

	public Role(RoleId id, User user) {
		this.id = id;
		this.user = user;
	}

	public RoleId getId() {
		return this.id;
	}

	public void setId(RoleId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
