package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 18, 2015 12:34:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String jmb;
	private String email;
	private String avatarPath;
	private boolean active;
	private Date registrationTime;
	private Date activationTime;
	private Set<Favorite> favorites = new HashSet<Favorite>(0);
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Listening> listenings = new HashSet<Listening>(0);
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<Rate> rates = new HashSet<Rate>(0);
	private Set<Playlist> playlists = new HashSet<Playlist>(0);

	public User() {
	}

	public User(String username, String password, String firstName,
			String lastName, String jmb, String email, boolean active,
			Date registeringTime) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.jmb = jmb;
		this.email = email;
		this.active = active;
		this.registrationTime = registeringTime;
	}

	public User(String username, String password, String firstName,
			String lastName, String jmb, String email, String avatarPath,
			boolean active, Date registeringTime, Date activationTime,
			Set<Favorite> favorites, Set<Event> events, Set<Comment> comments, Set<Listening> listenings, Set<Role> roles,
			Set<Rate> rates, Set<Playlist> playlists) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.jmb = jmb;
		this.email = email;
		this.avatarPath = avatarPath;
		this.active = active;
		this.registrationTime = registeringTime;
		this.activationTime = activationTime;
		this.favorites = favorites;
		this.events = events;
		this.comments = comments;
		this.listenings = listenings;
		this.roles = roles;
		this.rates = rates;
		this.playlists = playlists;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getJmb() {
		return this.jmb;
	}

	public void setJmb(String jmb) {
		this.jmb = jmb;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAvatarPath() {
		return this.avatarPath;
	}

	public void setAvatarPath(String avatarPath) {
		this.avatarPath = avatarPath;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getRegistrationTime() {
		return this.registrationTime;
	}

	public void setRegistrationTime(Date registeringTime) {
		this.registrationTime = registeringTime;
	}

	public Date getActivationTime() {
		return this.activationTime;
	}

	public void setActivationTime(Date activationTime) {
		this.activationTime = activationTime;
	}

	public Set<Favorite> getFavorites() {
		return this.favorites;
	}

	public void setFavorites(Set<Favorite> favorites) {
		this.favorites = favorites;
	}

	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	public Set<Listening> getListenings() {
		return this.listenings;
	}

	public void setListenings(Set<Listening> listenings) {
		this.listenings = listenings;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public Set<Rate> getRates() {
		return this.rates;
	}

	public void setRates(Set<Rate> rates) {
		this.rates = rates;
	}

	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

}
