package net.etfbl.muzickagroznica.model.entities;

// Generated Mar 13, 2015 10:37:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String jmb;
	private String email;
	private String avatarPath;
	private boolean active;
	private Date registeringTime;
	private Date activationTime;
	private Set favorites = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set listenings = new HashSet(0);
	private Set roles = new HashSet(0);
	private Set rates = new HashSet(0);
	private Set playlists = new HashSet(0);

	public User() {
	}

	public User(String username, String password, String firstName,
			String lastName, String jmb, String email, boolean active,
			Date registeringTime) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.jmb = jmb;
		this.email = email;
		this.active = active;
		this.registeringTime = registeringTime;
	}

	public User(String username, String password, String firstName,
			String lastName, String jmb, String email, String avatarPath,
			boolean active, Date registeringTime, Date activationTime,
			Set favorites, Set comments, Set listenings, Set roles, Set rates,
			Set playlists) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.jmb = jmb;
		this.email = email;
		this.avatarPath = avatarPath;
		this.active = active;
		this.registeringTime = registeringTime;
		this.activationTime = activationTime;
		this.favorites = favorites;
		this.comments = comments;
		this.listenings = listenings;
		this.roles = roles;
		this.rates = rates;
		this.playlists = playlists;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getJmb() {
		return this.jmb;
	}

	public void setJmb(String jmb) {
		this.jmb = jmb;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAvatarPath() {
		return this.avatarPath;
	}

	public void setAvatarPath(String avatarPath) {
		this.avatarPath = avatarPath;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getRegisteringTime() {
		return this.registeringTime;
	}

	public void setRegisteringTime(Date registeringTime) {
		this.registeringTime = registeringTime;
	}

	public Date getActivationTime() {
		return this.activationTime;
	}

	public void setActivationTime(Date activationTime) {
		this.activationTime = activationTime;
	}

	public Set getFavorites() {
		return this.favorites;
	}

	public void setFavorites(Set favorites) {
		this.favorites = favorites;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getListenings() {
		return this.listenings;
	}

	public void setListenings(Set listenings) {
		this.listenings = listenings;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

	public Set getRates() {
		return this.rates;
	}

	public void setRates(Set rates) {
		this.rates = rates;
	}

	public Set getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set playlists) {
		this.playlists = playlists;
	}

}
